### ISSUE TITLE
Suddenly unable to flash to `STM32F407VGTx` (STM32F407G-DISC1 ST-LINK V2.1)

### ISSUE THREAD

**Issue by mitchmindtree** [probe-rs/cargo-flash#36]
Thanks for your work on `cargo-flash`!

## The Bug

After (successfully) flashing a particular example onto my STM32F407G-DISC1 last night, `cargo-flash` no longer seems able to attach itself successfully to my board - as a result, I can't seem to flash a new program onto it.

## Details

Last night I was trying some different programs on my new STM32F407G-DISC1 using `cargo flash`. I was able to edit and flash the examples at the [stm32f407g-disc1 board support crate](https://github.com/stm32-rs/stm32f407g-disc) without any issues. Things were looking great! Here's an example of the command I was using:

```
cargo flash --release --example gpio_hal_blinky --chip STM32F407VGTx
```

I then tried adapting the [`rtic-examples` bluepill example](https://github.com/rtic-rs/rtic-examples/tree/master/rtic_v5/bluepill_blinky) to see if I could blink the stm32 crate with blinky. See [here for the adapted example](https://github.com/mitchmindtree/stm32f4xx-rtic-blinky) that I flashed onto the board with the following command:

```
cargo flash --release --chip STM32F407VGTx
```

Everything appeared to work nicely! Here's the output of the seemingly successful flash:

```
    Finished release [optimized + debuginfo] target(s) in 1m 07s                                                                              
    Flashing /home/mindtree/programming/rust/stm32f4xx-rtic/target/thumbv7em-none-eabihf/release/stm32f4xx-rtic                               
        WARN probe_rs::architecture::arm::core::m4 > Reason for halt has changed, old reason was Halted(Request), new reason is Exception     
        WARN probe_rs::architecture::arm::core::m4 > Reason for halt has changed, old reason was Halted(Breakpoint), new reason is Request    
        WARN probe_rs::architecture::arm::core::m4 > Reason for halt has changed, old reason was Halted(Request), new reason is Exception     
     Erasing sectors ✔ [00:00:00] [#################################################################]  16.00KB/ 16.00KB @  37.44KB/s (eta 0s )
 Programming pages   ✔ [00:00:00] [#################################################################]   4.00KB/  4.00KB @   3.47KB/s (eta 0s )
```

I can see that the example appears to run as expected, blinking the LED each time the `blink` software task gets called.

However, any of the following times I have attempted to flash a program `cargo-flash` gives a `JtagNoDeviceConnected` error. The first time I encountered the error, the output looked like this:

<details>
  <summary><b>Error output</b></summary>
  
  stdout+stderr:
  
  ```
   Compiling stm32f4xx-rtic v0.1.0 (/home/mindtree/programming/rust/stm32f4xx-rtic)                                                           
    Finished release [optimized + debuginfo] target(s) in 0.75s                                                                               
    Flashing /home/mindtree/programming/rust/stm32f4xx-rtic/target/thumbv7em-none-eabihf/release/stm32f4xx-rtic                               
        WARN probe_rs::probe::stlink > check_status failed: JtagNoDeviceConnected
       Error failed attaching to target

Caused by:
    0: An error with the usage of the probe occured
    1: An error specific to a probe type occured
    2: Command failed with status JtagNoDeviceConnected

Stack backtrace:
   0: cargo_flash::main_try
   1: cargo_flash::main
   2: std::rt::lang_start::{{closure}}
   3: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52 
      std::panicking::try::do_call
             at src/libstd/panicking.rs:297
      std::panicking::try
             at src/libstd/panicking.rs:274
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:51 
   4: main
   5: __libc_start_main
   6: _start
             at ../sysdeps/x86_64/start.S:120
```
</details>

Following this, I tried to flash the simpler `stm32f407g-disc1` board support crate blinky example (mentioned previously) as I knew it worked in the past, however the example appeared to give the same error.

I tried installing the `cargo-flash` `hard-reset` branch this morning to see if this would work instead. Here is command I used to try and build the blinky example again:

```
cargo flash --connect-under-reset --log debug --release --example gpio_hal_blinky --chip STM32F407VGTx
```

and here is the full output:

<details>
  <summary><b>Error output 2</b></summary>
  
  stdout+stderr:
```
   Compiling typenum v1.12.0
   Compiling semver-parser v0.7.0
   Compiling proc-macro2 v1.0.18
   Compiling unicode-xid v0.2.1
   Compiling memchr v2.3.3
   Compiling cortex-m v0.6.2
   Compiling stable_deref_trait v1.2.0
   Compiling syn v1.0.34
   Compiling version_check v0.1.5
   Compiling nb v1.0.0
   Compiling version_check v0.9.2
   Compiling vcell v0.1.2
   Compiling void v1.0.2
   Compiling cortex-m-rt v0.6.12
   Compiling r0 v0.2.2
   Compiling stm32f4 v0.11.0
   Compiling ssd1306 v0.2.6
   Compiling rand_core v0.5.1
   Compiling stm32f407g-disc v0.4.0 (/home/mindtree/programming/rust/stm32f407g-disc)
   Compiling panic-halt v0.2.0
   Compiling semver v0.9.0
   Compiling nb v0.1.3
   Compiling volatile-register v0.2.0
   Compiling nom v4.2.3
   Compiling rustc_version v0.2.3
   Compiling embedded-hal v0.2.4
   Compiling nom v5.1.2
   Compiling quote v1.0.7
   Compiling bare-metal v0.2.5
   Compiling cast v0.2.3
   Compiling generic-array v0.13.2
   Compiling generic-array v0.12.3
   Compiling tinytga v0.1.0
   Compiling micromath v1.0.1
   Compiling as-slice v0.1.3
   Compiling accelerometer v0.11.0
   Compiling aligned v0.3.2
   Compiling lis302dl v0.1.0
   Compiling tinybmp v0.1.1
   Compiling panic-itm v0.4.1
   Compiling embedded-graphics v0.4.9
   Compiling cortex-m-rt-macros v0.1.8
   Compiling stm32f4xx-hal v0.8.3
    Finished release [optimized + debuginfo] target(s) in 1m 04s
       DEBUG cargo_project > Project::query(path=/home/mindtree/programming/rust/stm32f407g-disc): root=/home/mindtree/programming/rust/stm32f407g-disc
       DEBUG cargo_project > workspace search: cwd=/home/mindtree/programming/rust
    Flashing /home/mindtree/programming/rust/stm32f407g-disc/target/thumbv7em-none-eabihf/release/examples/gpio_hal_blinky
       DEBUG jaylink       > libusb 1.0.23.11397
       DEBUG jaylink       > libusb has capability API: true
       DEBUG jaylink       > libusb has HID access: true
       DEBUG jaylink       > libusb has hotplug support: true
       DEBUG jaylink       > libusb can detach kernel driver: true
       DEBUG probe_rs::probe::daplink::tools > Attempting to open 0483:374b in CMSIS-DAP v1 mode
       DEBUG probe_rs::probe::stlink::usb_interface > Acquired libusb context.
       DEBUG probe_rs::probe::stlink::usb_interface > Aquired handle for probe
       DEBUG probe_rs::probe::stlink::usb_interface > Active config descriptor: ConfigDescriptor { bLength: 9, bDescriptorType: 2, wTotalLength: 128, bNumInterfaces: 4, bConfigurationValue: 1, iConfiguration: 0, bmAttributes: 128, bMaxPower: 200, extra: None }
       DEBUG probe_rs::probe::stlink::usb_interface > Device descriptor: DeviceDescriptor { bLength: 18, bDescriptorType: 1, bcdUSB: 512, bDeviceClass: 239, bDeviceSubClass: 2, bDeviceProtocol: 1, bMaxPacketSize: 64, idVendor: 1155, idProduct: 14155, bcdDevice: 256, iManufacturer: 1, iProduct: 2, iSerialNumber: 3, bNumConfigurations: 1 }
       DEBUG probe_rs::probe::stlink::usb_interface > Claimed interface 0 of USB device.
       DEBUG probe_rs::probe::stlink::usb_interface > Succesfully attached to STLink.
       DEBUG probe_rs::probe::stlink                > Initializing STLink...
       DEBUG probe_rs::probe::stlink                > Current device mode: Jtag
       DEBUG probe_rs::probe::stlink                > STLink version: (2, 37)
        INFO cargo_flash                            > Protocol speed 1800 kHz
       DEBUG probe_rs::probe                        > Asserting reset
       DEBUG probe_rs::probe::stlink                > attach(Swd)
       DEBUG probe_rs::probe::stlink                > Current device mode: Jtag
       DEBUG probe_rs::probe::stlink                > Switching protocol to SWD
       DEBUG probe_rs::probe::stlink                > Successfully initialized SWD.
       DEBUG probe_rs::config::registry             > Searching registry for chip with name STM32F407VGTx
       DEBUG probe_rs::architecture::arm::communication_interface > Debug Port version: DPv1
       DEBUG probe_rs::architecture::arm::communication_interface > Reading DP register DPIDR
       DEBUG probe_rs::architecture::arm::communication_interface > Read    DP register DPIDR, value=0x2ba01477
       DEBUG probe_rs::architecture::arm::communication_interface > DebugPort ID:  DebugPortId {
    revision: 0x2,
    part_no: 0xba,
    version: DPv1,
    min_dp_support: NotImplemented,
    designer: JEP106Code({ cc: 0x04, id: 0x3b } => Some("ARM Ltd")),
}
       DEBUG probe_rs::architecture::arm::communication_interface > Writing DP register ABORT, value=0x0000003c
       DEBUG probe_rs::architecture::arm::communication_interface > Writing DP register SELECT, value=0x00000000
       DEBUG probe_rs::architecture::arm::communication_interface > Requesting debug power
       DEBUG probe_rs::architecture::arm::communication_interface > Writing DP register CTRL/STAT, value=0x50000000
       DEBUG probe_rs::architecture::arm::communication_interface > Reading DP register CTRL/STAT
       DEBUG probe_rs::architecture::arm::communication_interface > Read    DP register CTRL/STAT, value=0xf0000040
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register CSW, value=0x63000010
       DEBUG probe_rs::architecture::arm::communication_interface > Reading register CSW
       DEBUG probe_rs::architecture::arm::communication_interface > Read register    CSW, value=0x23000050
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register CSW, value=0x63000012
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register TAR, value=0xE000EDF0
       DEBUG probe_rs::architecture::arm::communication_interface > Reading register DRW
       DEBUG probe_rs::architecture::arm::communication_interface > Read register    DRW, value=0x02010001
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register CSW, value=0x63000012
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register TAR, value=0xE000ED30
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register DRW, value=0x0000001F
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register CSW, value=0x63000012
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register CSW, value=0x63000012
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register TAR, value=0xE000EDF0
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register DRW, value=0xA05F0001
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register CSW, value=0x63000012
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register CSW, value=0x63000010
       DEBUG probe_rs::architecture::arm::communication_interface > Reading register CSW
       DEBUG probe_rs::architecture::arm::communication_interface > Read register    CSW, value=0x23000050
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register CSW, value=0x63000012
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register TAR, value=0xE000EDFC
       DEBUG probe_rs::architecture::arm::communication_interface > Reading register DRW
       DEBUG probe_rs::architecture::arm::communication_interface > Read register    DRW, value=0x01000000
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register CSW, value=0x63000012
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register TAR, value=0xE000EDFC
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register DRW, value=0x01000001
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register CSW, value=0x63000012
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register CSW, value=0x63000012
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register TAR, value=0xE000EDF0
       DEBUG probe_rs::architecture::arm::communication_interface > Reading register DRW
       DEBUG probe_rs::architecture::arm::communication_interface > Read register    DRW, value=0x02010001
       DEBUG probe_rs::probe                                      > Deasserting target reset
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register CSW, value=0x63000010
       DEBUG probe_rs::architecture::arm::communication_interface > Reading register CSW
       DEBUG probe_rs::architecture::arm::communication_interface > Read register    CSW, value=0x23000050
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register CSW, value=0x63000012
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register TAR, value=0xE000EDF0
       DEBUG probe_rs::architecture::arm::communication_interface > Reading register DRW
       DEBUG probe_rs::architecture::arm::communication_interface > Read register    DRW, value=0x02030003
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register CSW, value=0x63000012
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register TAR, value=0xE000EDF0
       DEBUG probe_rs::architecture::arm::communication_interface > Reading register DRW
       DEBUG probe_rs::architecture::arm::communication_interface > Read register    DRW, value=0x00030003
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register CSW, value=0x63000012
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register TAR, value=0xE000ED30
       DEBUG probe_rs::architecture::arm::communication_interface > Reading register DRW
       DEBUG probe_rs::architecture::arm::communication_interface > Read register    DRW, value=0x00000008
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register CSW, value=0x63000012
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register TAR, value=0xE000ED30
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register DRW, value=0x0000001F
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register CSW, value=0x63000012
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register CSW, value=0x63000012
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register TAR, value=0xE000EDFC
       DEBUG probe_rs::architecture::arm::communication_interface > Reading register DRW
       DEBUG probe_rs::architecture::arm::communication_interface > Read register    DRW, value=0x01000001
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register CSW, value=0x63000012
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register TAR, value=0xE000EDFC
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register DRW, value=0x01000000
       DEBUG probe_rs::architecture::arm::communication_interface > Writing register CSW, value=0x63000012
       Error failed to flash /home/mindtree/programming/rust/stm32f407g-disc/target/thumbv7em-none-eabihf/release/examples/gpio_hal_blinky

Caused by:
    0: Error while flashing
    1: Something during the interaction with the core went wrong
    2: A core architecture specific error occured
    3: Failed to read register DRW at address 0x0000000c because: An error specific to a probe type occured
    4: An error specific to a probe type occured
    5: Command failed with status SwdDpWait

Stack backtrace:
   0: anyhow::context::<impl anyhow::Context<T,E> for core::result::Result<T,E>>::with_context
   1: cargo_flash::main_try
   2: cargo_flash::main
   3: std::rt::lang_start::{{closure}}
   4: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
      std::panicking::try::do_call
             at src/libstd/panicking.rs:297
      std::panicking::try
             at src/libstd/panicking.rs:274
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:51
   5: main
   6: __libc_start_main
   7: _start
             at ../sysdeps/x86_64/start.S:120
```
</details>

This time we seem to get a bit further, instead running into a `Command failed with status SwdDpWait` error.

## Theories

Looking at my rtic blink demo src (that seems to have caused these issues), the only thing that stands out to me is [the way the clocks are configured](https://github.com/mitchmindtree/stm32f4xx-rtic-blinky/blob/master/src/main.rs#L30-L35):
```rust
        // Setup clocks
        let rcc = device.RCC.constrain();
        let _clocks = rcc
            .cfgr
            .use_hse(8.mhz())
            .sysclk(72.mhz())
            .pclk1(36.mhz())
            .freeze();
```

This config is left over from the bluepill config, I managed to miss this when updating the code! I think likely it should have looked like this:
```rust
        let rcc = device.RCC.constrain();
        let _clocks = rcc.cfgr.sysclk(168.mhz()).freeze();
```

Is it possible that my odd clock settings might have caused some issues with the debug interface `cargo-flash` tries to use? Or do you think something else might be going on? Any advice on other approaches to try would be appreciated!

## System Info

cargo-flash 0.8.0
rustc 1.46.0-nightly (feb3536eb 2020-06-09)
cargo 1.45.0-nightly (40ebd5220 2020-06-01)
nixos, linux 5.7.2

**Comment by mitchmindtree** [comment]
Possibly related: probe-rs/probe-rs#216

**Comment by mitchmindtree** [comment]
After forcing the STM32F407G-DISC1 to stay in the bootloader on reset by setting the BOOT0 pin high (connecting it to VDD), I was then able to successfully `cargo flash` the device again!

I'll leave this open in case you'd still like to see this addressed.

**Comment by adamgreig** [comment]
Are you able to reproduce the issue again if you re-flash the bad firmware? And if so, while it's failing with cargo-flash, are you able to connect or reprogram using other tools, such as st-util, openocd, or pyocd? From a quick look at  your firmware nothing except the HSE part seems suspicious. I think by default the HSE on that board is 12MHz, so you might have been overclocking your board 50% which could have caused the issue. Perhaps you could see if `use_hse(12.mhz())` makes a difference?

**Comment by mitchmindtree** [comment]
Hi @adamgreig!

Yes I can recreate the issue by flashing the bad firmware again.

I changed the clock setup to:

```rust
        let rcc = device.RCC.constrain();
        let _clocks = rcc.cfgr.sysclk(168.mhz()).freeze();
```

But I still run into the same issue. Here is the generated `target/rtic-expansion.rs` in case it you're curious to see what gets generated:

<details>
  <summary><b>rtic-expansion.rs</b></summary>
  
  Generated code:

```rust
#[allow(non_snake_case)]
fn init(cx: init::Context) -> init::LateResources {
    let mut core = cx.core;
    core.DWT.enable_cycle_counter();
    let device: stm32f4xx_hal::stm32::Peripherals = cx.device;
    let rcc = device.RCC.constrain();
    let _clocks = rcc.cfgr.sysclk(CYCLE_HZ.hz()).freeze();
    let gpiod = device.GPIOD.split();
    let mut led = gpiod.pd13.into_push_pull_output();
    led.set_low().unwrap();
    cx.schedule.blink(cx.start + CYCLE_HZ.cycles()).unwrap();
    init::LateResources { led }
}
#[allow(non_snake_case)]
fn blink(cx: blink::Context) {
    use rtic::Mutex as _;
    cx.resources.led.toggle().unwrap();
    cx.schedule.blink(cx.scheduled + CYCLE_HZ.cycles()).unwrap();
}
#[doc = r" Resources initialized at runtime"]
#[allow(non_snake_case)]
pub struct initLateResources {
    pub led: PD13<Output<PushPull>>,
}
#[allow(non_snake_case)]
#[doc = "Initialization function"]
pub mod init {
    #[doc = "Tasks that can be `schedule`-d from this context"]
    #[derive(Clone, Copy)]
    pub struct Schedule {
        _not_send: core::marker::PhantomData<*mut ()>,
    }
    #[doc(inline)]
    pub use super::initLateResources as LateResources;
    #[doc = r" Execution context"]
    pub struct Context {
        #[doc = r" System start time = `Instant(0 /* cycles */)`"]
        pub start: <rtic::cyccnt::CYCCNT as rtic::Monotonic>::Instant,
        #[doc = r" Core (Cortex-M) peripherals minus the SysTick"]
        pub core: rtic::Peripherals,
        #[doc = r" Device peripherals"]
        pub device: stm32f4xx_hal::stm32::Peripherals,
        #[doc = "Tasks that can be `schedule`-d from this context"]
        pub schedule: Schedule,
    }
    impl Context {
        #[inline(always)]
        pub unsafe fn new(core: rtic::Peripherals) -> Self {
            Context {
                start: <rtic::cyccnt::CYCCNT as rtic::Monotonic>::zero(),
                device: stm32f4xx_hal::stm32::Peripherals::steal(),
                core,
                schedule: Schedule {
                    _not_send: core::marker::PhantomData,
                },
            }
        }
    }
}
#[allow(non_snake_case)]
#[doc = "Resources `blink` has access to"]
pub struct blinkResources<'a> {
    pub led: &'a mut PD13<Output<PushPull>>,
}
#[allow(non_snake_case)]
#[doc = "Software task"]
pub mod blink {
    #[doc(inline)]
    pub use super::blinkResources as Resources;
    #[doc = "Tasks that can be `schedule`-d from this context"]
    #[derive(Clone, Copy)]
    pub struct Schedule<'a> {
        priority: &'a rtic::export::Priority,
    }
    impl<'a> Schedule<'a> {
        #[doc(hidden)]
        #[inline(always)]
        pub unsafe fn priority(&self) -> &rtic::export::Priority {
            &self.priority
        }
    }
    #[doc = r" Execution context"]
    pub struct Context<'a> {
        #[doc = r" The time at which this task was scheduled to run"]
        pub scheduled: <rtic::cyccnt::CYCCNT as rtic::Monotonic>::Instant,
        #[doc = r" Resources this task has access to"]
        pub resources: Resources<'a>,
        #[doc = "Tasks that can be `schedule`-d from this context"]
        pub schedule: Schedule<'a>,
    }
    impl<'a> Context<'a> {
        #[inline(always)]
        pub unsafe fn new(
            priority: &'a rtic::export::Priority,
            instant: <rtic::cyccnt::CYCCNT as rtic::Monotonic>::Instant,
        ) -> Self {
            Context {
                scheduled: instant,
                resources: Resources::new(priority),
                schedule: Schedule { priority },
            }
        }
    }
}
#[doc = r" Implementation details"]
const APP: () = {
    #[doc = r" Always include the device crate which contains the vector table"]
    use stm32f4xx_hal::stm32 as _;
    #[cfg(core = "1")]
    compile_error!("specified 1 core but tried to compile for more than 1 core");
    #[allow(non_upper_case_globals)]
    #[link_section = ".uninit.rtic0"]
    static mut led: core::mem::MaybeUninit<PD13<Output<PushPull>>> =
        core::mem::MaybeUninit::uninit();
    #[doc = r" Queue version of a free-list that keeps track of empty slots in"]
    #[doc = r" the following buffers"]
    static mut blink_S0_FQ: rtic::export::SCFQ<rtic::export::consts::U1> =
        rtic::export::Queue(unsafe { rtic::export::iQueue::u8_sc() });
    struct blink_S0_FQ<'a> {
        priority: &'a rtic::export::Priority,
    }
    impl<'a> rtic::Mutex for blink_S0_FQ<'a> {
        type T = rtic::export::SCFQ<rtic::export::consts::U1>;
        #[inline(always)]
        fn lock<R>(
            &mut self,
            f: impl FnOnce(&mut rtic::export::SCFQ<rtic::export::consts::U1>) -> R,
        ) -> R {
            #[doc = r" Priority ceiling"]
            const CEILING: u8 = 1u8;
            unsafe {
                rtic::export::lock(
                    &mut blink_S0_FQ,
                    self.priority,
                    CEILING,
                    stm32f4xx_hal::stm32::NVIC_PRIO_BITS,
                    f,
                )
            }
        }
    }
    #[link_section = ".uninit.rtic1"]
    #[doc = r" Buffer that holds the instants associated to the inputs of a task"]
    static mut blink_S0_INSTANTS: [core::mem::MaybeUninit<
        <rtic::cyccnt::CYCCNT as rtic::Monotonic>::Instant,
    >; 1] = [core::mem::MaybeUninit::uninit()];
    #[link_section = ".uninit.rtic2"]
    #[doc = r" Buffer that holds the inputs of a task"]
    static mut blink_S0_INPUTS: [core::mem::MaybeUninit<()>; 1] =
        [core::mem::MaybeUninit::uninit()];
    impl<'a> blinkResources<'a> {
        #[inline(always)]
        unsafe fn new(priority: &'a rtic::export::Priority) -> Self {
            blinkResources {
                led: &mut *led.as_mut_ptr(),
            }
        }
    }
    #[allow(non_camel_case_types)]
    #[derive(Clone, Copy)]
    #[doc = "Software tasks spawned from core #0 to be dispatched at priority level 1 by core #0"]
    enum R0_P1_S0_T {
        blink,
    }
    #[doc = "Queue of tasks sent by core #0 ready to be dispatched by core #0 at priority level 1"]
    static mut R0_P1_S0_RQ: rtic::export::SCRQ<R0_P1_S0_T, rtic::export::consts::U1> =
        rtic::export::Queue(unsafe { rtic::export::iQueue::u8_sc() });
    struct R0_P1_S0_RQ<'a> {
        priority: &'a rtic::export::Priority,
    }
    impl<'a> rtic::Mutex for R0_P1_S0_RQ<'a> {
        type T = rtic::export::SCRQ<R0_P1_S0_T, rtic::export::consts::U1>;
        #[inline(always)]
        fn lock<R>(
            &mut self,
            f: impl FnOnce(&mut rtic::export::SCRQ<R0_P1_S0_T, rtic::export::consts::U1>) -> R,
        ) -> R {
            #[doc = r" Priority ceiling"]
            const CEILING: u8 = 1u8;
            unsafe {
                rtic::export::lock(
                    &mut R0_P1_S0_RQ,
                    self.priority,
                    CEILING,
                    stm32f4xx_hal::stm32::NVIC_PRIO_BITS,
                    f,
                )
            }
        }
    }
    #[allow(non_snake_case)]
    #[doc = "Interrupt handler used by core #0 to dispatch tasks at priority 1"]
    #[no_mangle]
    unsafe fn EXTI0() {
        #[doc = r" The priority of this interrupt handler"]
        const PRIORITY: u8 = 1u8;
        rtic::export::run(PRIORITY, || {
            while let Some((task, index)) = R0_P1_S0_RQ.split().1.dequeue() {
                match task {
                    R0_P1_S0_T::blink => {
                        let () = blink_S0_INPUTS
                            .get_unchecked(usize::from(index))
                            .as_ptr()
                            .read();
                        let instant = blink_S0_INSTANTS
                            .get_unchecked(usize::from(index))
                            .as_ptr()
                            .read();
                        blink_S0_FQ.split().0.enqueue_unchecked(index);
                        let priority = &rtic::export::Priority::new(PRIORITY);
                        crate::blink(blink::Context::new(priority, instant))
                    }
                }
            }
        });
    }
    #[doc = "Tasks that can be scheduled from core #0"]
    #[allow(non_camel_case_types)]
    #[derive(Clone, Copy)]
    enum T0 {
        blink,
    }
    #[doc = "Core #0 timer queue"]
    static mut TQ0: rtic::export::TimerQueue<rtic::cyccnt::CYCCNT, T0, rtic::export::consts::U1> =
        rtic::export::TimerQueue(rtic::export::BinaryHeap(rtic::export::iBinaryHeap::new()));
    struct TQ0<'a> {
        priority: &'a rtic::export::Priority,
    }
    impl<'a> rtic::Mutex for TQ0<'a> {
        type T = rtic::export::TimerQueue<rtic::cyccnt::CYCCNT, T0, rtic::export::consts::U1>;
        #[inline(always)]
        fn lock<R>(
            &mut self,
            f: impl FnOnce(
                &mut rtic::export::TimerQueue<rtic::cyccnt::CYCCNT, T0, rtic::export::consts::U1>,
            ) -> R,
        ) -> R {
            #[doc = r" Priority ceiling"]
            const CEILING: u8 = 1u8;
            unsafe {
                rtic::export::lock(
                    &mut TQ0,
                    self.priority,
                    CEILING,
                    stm32f4xx_hal::stm32::NVIC_PRIO_BITS,
                    f,
                )
            }
        }
    }
    #[no_mangle]
    unsafe fn SysTick() {
        use rtic::Mutex as _;
        #[doc = r" The priority of this handler"]
        const PRIORITY: u8 = 1u8;
        rtic::export::run(PRIORITY, || {
            while let Some((task, index)) = (TQ0 {
                priority: &rtic::export::Priority::new(PRIORITY),
            })
            .lock(
                #[inline(always)]
                |tq| tq.dequeue(),
            ) {
                match task {
                    T0::blink => {
                        (R0_P1_S0_RQ {
                            priority: &rtic::export::Priority::new(PRIORITY),
                        })
                        .lock(|rq| rq.split().0.enqueue_unchecked((R0_P1_S0_T::blink, index)));
                        rtic::pend(stm32f4xx_hal::stm32::Interrupt::EXTI0);
                    }
                }
            }
        });
    }
    impl init::Schedule {
        fn blink(
            &self,
            instant: <rtic::cyccnt::CYCCNT as rtic::Monotonic>::Instant,
        ) -> Result<(), ()> {
            unsafe {
                use rtic::Mutex as _;
                let input = ();
                if let Some(index) = blink_S0_FQ.dequeue() {
                    blink_S0_INPUTS
                        .get_unchecked_mut(usize::from(index))
                        .as_mut_ptr()
                        .write(input);
                    blink_S0_INSTANTS
                        .get_unchecked_mut(usize::from(index))
                        .as_mut_ptr()
                        .write(instant);
                    let nr = rtic::export::NotReady {
                        instant,
                        index,
                        task: T0::blink,
                    };
                    TQ0.enqueue_unchecked(nr);
                    Ok(())
                } else {
                    Err(input)
                }
            }
        }
    }
    unsafe fn schedule_blink_S0(
        priority: &rtic::export::Priority,
        instant: <rtic::cyccnt::CYCCNT as rtic::Monotonic>::Instant,
    ) -> Result<(), ()> {
        unsafe {
            use rtic::Mutex as _;
            let input = ();
            if let Some(index) = (blink_S0_FQ { priority }).lock(|fq| fq.split().1.dequeue()) {
                blink_S0_INPUTS
                    .get_unchecked_mut(usize::from(index))
                    .as_mut_ptr()
                    .write(input);
                blink_S0_INSTANTS
                    .get_unchecked_mut(usize::from(index))
                    .as_mut_ptr()
                    .write(instant);
                let nr = rtic::export::NotReady {
                    instant,
                    index,
                    task: T0::blink,
                };
                (TQ0 { priority }).lock(|tq| tq.enqueue_unchecked(nr));
                Ok(())
            } else {
                Err(input)
            }
        }
    }
    impl<'a> blink::Schedule<'a> {
        #[inline(always)]
        fn blink(
            &self,
            instant: <rtic::cyccnt::CYCCNT as rtic::Monotonic>::Instant,
        ) -> Result<(), ()> {
            unsafe { schedule_blink_S0(self.priority(), instant) }
        }
    }
    #[no_mangle]
    unsafe extern "C" fn main() -> ! {
        let _TODO: () = ();
        rtic::export::assert_send::<PD13<Output<PushPull>>>();
        rtic::export::interrupt::disable();
        (0..1u8).for_each(|i| blink_S0_FQ.enqueue_unchecked(i));
        let mut core: rtic::export::Peripherals = core::mem::transmute(());
        let _ = [(); ((1 << stm32f4xx_hal::stm32::NVIC_PRIO_BITS) - 1u8 as usize)];
        core.NVIC.set_priority(
            stm32f4xx_hal::stm32::Interrupt::EXTI0,
            rtic::export::logical2hw(1u8, stm32f4xx_hal::stm32::NVIC_PRIO_BITS),
        );
        rtic::export::NVIC::unmask(stm32f4xx_hal::stm32::Interrupt::EXTI0);
        let _ = [(); ((1 << stm32f4xx_hal::stm32::NVIC_PRIO_BITS) - 1u8 as usize)];
        core.SCB.set_priority(
            rtic::export::SystemHandler::SysTick,
            rtic::export::logical2hw(1u8, stm32f4xx_hal::stm32::NVIC_PRIO_BITS),
        );
        core.SYST
            .set_clock_source(rtic::export::SystClkSource::Core);
        core.SYST.enable_counter();
        core.DCB.enable_trace();
        core.SCB.scr.modify(|r| r | 1 << 1);
        let late = crate::init(init::Context::new(core.into()));
        led.as_mut_ptr().write(late.led);
        <rtic::cyccnt::CYCCNT as rtic::Monotonic>::reset();
        rtic::export::interrupt::enable();
        loop {
            rtic::export::wfi()
        }
    }
};
```
</details>

I haven't tried reprogramming with other tools yet - I'll have a go using st-util now and report back.

**Comment by mitchmindtree** [comment]
OK, I haven't tried any other tools yet, but I've managed to get the example to work!

By declaring an `rtic` `#[idle]` task, the issue no longer occurs and I can reprogram the board using `cargo flash` without issues. Here's the `idle` function I've used:

```rust
    #[idle]
    fn idle(_: idle::Context) -> ! {
        loop {
            core::sync::atomic::spin_loop_hint();
        }
    }
```

I wonder why this might be the case?

**Comment by adamgreig** [comment]
Oh, of course, it's because the [default idle](https://github.com/rtic-rs/cortex-m-rtic/blob/6e233bec029810716c5a48113b22f4446204cfab/macros/src/codegen/idle.rs#L87) in RTIC calls `WFI` which puts the device to sleep, from which it can't be accessed by the debugger unless you first configure "debug in sleep" mode. Putting your own idle is probably the way to go. I would have expected that connecting under reset in probe-rs should fix this though.

**Comment by Yatekii** [comment]
Yeah, I believe that this is still not fully fixed.

Maybe I should flash a WFI example onto one of my kits to debug this! We'll see during oxidize :)
